Repository datagov-cz/ontoGrapher, pull requests merged in 2021-02, with the labels that each got.

#221 Issue 211
  package-lock.json
  src/locale/help.ts
  src/panels/menu/help/HelpCheatSheet.tsx
  src/panels/menu/help/HelpMain.tsx
  src/panels/menu/misc/HelpModal.tsx
Labels: documentation

#222 Issue 217
  src/config/Variables.ts
  src/main/DiagramApp.tsx
  src/main/DiagramCanvas.tsx
  src/queries/QueryBuilder.ts
  src/react-app-env.d.ts
Labels: bug

#229 Startup slowdown/freeze fix
  src/interface/SPARQLInterface.ts
Labels: bug

#227 "Report issue" button
  package-lock.json
  package.json
  src/config/ColorPool.ts
  src/config/Locale.ts
  src/function/FunctionEditVars.ts
  src/function/FunctionGetVars.ts
  src/locale/cs.json
  src/locale/cs.ts
  src/locale/cschangelog.ts
  src/locale/cshelp.ts
  src/locale/en.json
  src/locale/en.ts
  src/locale/enchangelog.ts
  src/locale/enhelp.ts
  src/locale/help.ts
  src/main/DiagramApp.tsx
  src/panels/MenuPanel.tsx
  src/panels/menu/MenuPanelAbout.tsx
  src/panels/menu/MenuPanelReport.tsx
  src/panels/menu/MenuPanelSwitchRepresentation.tsx
  src/panels/menu/help/HelpCheatSheet.tsx
  src/panels/menu/help/HelpMain.tsx
  src/panels/menu/misc/AboutModal.tsx
  src/panels/menu/misc/HelpModal.tsx
  src/panels/menu/view/MenuPanelSwitchColors.tsx
  src/scss/panels/MenuPanel.scss
Labels: enhancement

#226 Export issue fix
  src/queries/UpdateConnectionQueries.ts
Labels: bug

#223 Issue 209
  src/components/InterfaceStatus.tsx
  src/config/RestrictionConfig.ts
  src/config/Restrictions.ts
  src/config/Variables.ts
  src/datatypes/Cardinality.ts
  src/datatypes/ConnectionObject.ts
  src/datatypes/Restriction.ts
  src/datatypes/RestrictionObject.ts
  src/function/FunctionCreateVars.ts
  src/function/FunctionDiagram.ts
  src/function/FunctionDraw.ts
  src/function/FunctionEditVars.ts
  src/function/FunctionGetVars.ts
  src/function/FunctionGraph.ts
  src/function/FunctionLink.ts
  src/function/FunctionRestriction.ts
  src/interface/ContextInterface.ts
  src/interface/JSONInterface.ts
  src/interface/SPARQLInterface.ts
  src/interface/TransactionInterface.ts
  src/interface/ValidationInterface.ts
  src/main/DiagramApp.tsx
  src/main/DiagramCanvas.tsx
  src/main/NewElemModal.tsx
  src/main/NewLinkModal.tsx
  src/panels/ItemPanel.tsx
  src/panels/ValidationPanel.tsx
  src/panels/diagram/DiagramAdd.tsx
  src/panels/element/PackageFolder.tsx
  src/panels/menu/MenuPanelLogout.tsx
  src/panels/menu/MenuPanelSwitchRepresentation.tsx
  src/panels/menu/widget/ZoomWidget.tsx
  src/panels/modal/ModalRemoveDiagram.tsx
  src/panels/modal/ModalRemoveItem.tsx
  src/queries/UpdateConnectionQueries.ts
  src/queries/UpdateMiscQueries.ts
Labels: bug
